### ISSUE TITLE
Word2Vec in StellarGraph

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#255] opened 2018-10-08 00:01 UTC
### Description

Random walk-based representation learning methods in StellarGraph, e.g., node2vec, metapath2vec, deepwalk, make use of Gensim's implementation of word2vec. This issue is about implementing word2vec as part of StellarGraph. 

Furthermore, we would like to improve the implementation so that we can extend word2vec such that it learns a node representation in conjunction with the downstream task; the latter should be possible but optional.

### User Story
As a: Research Engineer and StellarGraph developer
I want: an implementation of the Word2Vec algorithm consistent with the StellarGraph API as well as enhanced such that node representation can be learned together with the downstream task
so that: I can remove dependence of StellarGraph on Gensim and develop better graph ML models (with the extended Word2Vec algorithm).

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Unit tests
- [ ] Branch and Pull Request build on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by youph** [comment] 2018-10-10 02:13
This is a duplicate of

**Comment by yvonnegh** [comment] 2020-01-07 04:49
Daokun to finish before going away on leave 14 Jan (return Feb).  Yuriy to hopefully review if he has capacity.

**Closed** 2020-05-15 01:05 UTC
Labels: enhancement, sg-library
