### ISSUE TITLE
Problem in GCN link prediction example 

### ISSUE THREAD

**Issue by davidho27941** [stellargraph/stellargraph#1766] opened 2020-07-08 02:17 UTC
### Describe the bug

It seems that the GCN link prediction example doesn't perform the same performance in the doc. And the GCN seems didn't learn something from the data, I am not sure why this happen.

### To Reproduce

1. Go to the colab example code https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/link-prediction/gcn-link-prediction.ipynb#scrollTo=cW8U-jvPKdob.
2. Just run all the commands.
3. Can't get the same performance in https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/gcn-link-prediction.html, the acc is close to 0 in the reproduction of example.

I just run the code w/o any modification.

### Environment

Operating system: 1. Ubuntu      2. colab

Python version: 1. python3.6.9        2. colab example default

Package versions: 1. stellargraph==1.2.1, tensorflow==2.2.0      2. colab example default

```
<IPython.core.display.HTML object>
StellarGraph: Undirected multigraph
 Nodes: 2708, Edges: 5429

 Node types:
  paper: [2708]
    Features: float32 vector, length 1440
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5429]
        Weights: all 1 (default)
        Features: none
** Sampled 542 positive and 542 negative edges. **
** Sampled 488 positive and 488 negative edges. **
Using GCN (local pooling) filters...
Using GCN (local pooling) filters...
2020-07-08 02:02:51.125100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
1/1 [==============================] - 0s 261us/step - loss: 1.7441 - acc: 0.0000e+00
1/1 [==============================] - 0s 372us/step - loss: 1.7190 - acc: 0.0000e+00

Train Set Metrics of the initial (untrained) model:
        loss: 1.7441
        acc: 0.0000

Test Set Metrics of the initial (untrained) model:
        loss: 1.7190
        acc: 0.0000
Epoch 1/50
1/1 - 0s - loss: 1.7230 - acc: 0.0000e+00 - val_loss: 1.6174 - val_acc: 0.0000e+00
Epoch 2/50
1/1 - 0s - loss: 1.8744 - acc: 0.0000e+00 - val_loss: 0.6929 - val_acc: 0.0000e+00
Epoch 3/50
1/1 - 0s - loss: 0.7559 - acc: 0.0000e+00 - val_loss: 0.8678 - val_acc: 0.0000e+00
Epoch 4/50
1/1 - 0s - loss: 0.8746 - acc: 0.0000e+00 - val_loss: 0.9703 - val_acc: 0.0000e+00
Epoch 5/50
1/1 - 0s - loss: 0.9689 - acc: 0.0000e+00 - val_loss: 0.9082 - val_acc: 0.0000e+00
Epoch 6/50
1/1 - 0s - loss: 0.8899 - acc: 0.0000e+00 - val_loss: 0.7689 - val_acc: 0.0000e+00
Epoch 7/50
1/1 - 0s - loss: 0.7362 - acc: 0.0000e+00 - val_loss: 0.6734 - val_acc: 0.0000e+00
Epoch 8/50
1/1 - 0s - loss: 0.6950 - acc: 0.0000e+00 - val_loss: 0.7262 - val_acc: 0.0000e+00
Epoch 9/50
1/1 - 0s - loss: 0.7597 - acc: 0.0000e+00 - val_loss: 0.9009 - val_acc: 0.0000e+00
Epoch 10/50
1/1 - 0s - loss: 1.0559 - acc: 0.0000e+00 - val_loss: 0.8252 - val_acc: 0.0000e+00
Epoch 11/50
1/1 - 0s - loss: 0.9358 - acc: 0.0000e+00 - val_loss: 0.6823 - val_acc: 0.0000e+00
Epoch 12/50
1/1 - 0s - loss: 0.7335 - acc: 0.0000e+00 - val_loss: 0.6319 - val_acc: 0.0000e+00
Epoch 13/50
1/1 - 0s - loss: 0.5645 - acc: 0.0000e+00 - val_loss: 0.6511 - val_acc: 0.0000e+00
Epoch 14/50
1/1 - 0s - loss: 0.6124 - acc: 0.0000e+00 - val_loss: 0.6859 - val_acc: 0.0000e+00
Epoch 15/50
1/1 - 0s - loss: 0.6148 - acc: 0.0000e+00 - val_loss: 0.7000 - val_acc: 0.0000e+00
Epoch 16/50
1/1 - 0s - loss: 0.6342 - acc: 0.0000e+00 - val_loss: 0.6994 - val_acc: 0.0000e+00
Epoch 17/50
1/1 - 0s - loss: 0.6002 - acc: 0.0000e+00 - val_loss: 0.6820 - val_acc: 0.0000e+00
Epoch 18/50
1/1 - 0s - loss: 0.5741 - acc: 0.0000e+00 - val_loss: 0.6816 - val_acc: 0.0000e+00
Epoch 19/50
1/1 - 0s - loss: 0.5270 - acc: 0.0000e+00 - val_loss: 0.6888 - val_acc: 0.0000e+00
Epoch 20/50
1/1 - 0s - loss: 0.5358 - acc: 0.0000e+00 - val_loss: 0.7120 - val_acc: 0.0000e+00
Epoch 21/50
1/1 - 0s - loss: 0.5582 - acc: 0.0000e+00 - val_loss: 0.7397 - val_acc: 0.0000e+00
Epoch 22/50
1/1 - 0s - loss: 0.6449 - acc: 0.0000e+00 - val_loss: 0.7800 - val_acc: 0.0000e+00
Epoch 23/50
1/1 - 0s - loss: 0.5558 - acc: 0.0000e+00 - val_loss: 0.6514 - val_acc: 0.0000e+00
Epoch 24/50
1/1 - 0s - loss: 0.5180 - acc: 0.0000e+00 - val_loss: 0.6666 - val_acc: 0.0000e+00
Epoch 25/50
1/1 - 0s - loss: 0.5070 - acc: 0.0000e+00 - val_loss: 0.6780 - val_acc: 0.0000e+00
Epoch 26/50
1/1 - 0s - loss: 0.5492 - acc: 0.0000e+00 - val_loss: 0.7167 - val_acc: 0.0000e+00
Epoch 27/50
1/1 - 0s - loss: 0.5637 - acc: 0.0000e+00 - val_loss: 0.7343 - val_acc: 0.0000e+00
Epoch 28/50
1/1 - 0s - loss: 0.6122 - acc: 0.0000e+00 - val_loss: 0.7493 - val_acc: 0.0000e+00
Epoch 29/50
1/1 - 0s - loss: 0.6122 - acc: 0.0000e+00 - val_loss: 0.7420 - val_acc: 0.0000e+00
Epoch 30/50
1/1 - 0s - loss: 0.5376 - acc: 0.0000e+00 - val_loss: 0.7160 - val_acc: 0.0000e+00
Epoch 31/50
1/1 - 0s - loss: 0.5866 - acc: 0.0000e+00 - val_loss: 0.6874 - val_acc: 0.0000e+00
Epoch 32/50
1/1 - 0s - loss: 0.5429 - acc: 0.0000e+00 - val_loss: 0.6786 - val_acc: 0.0000e+00
Epoch 33/50
1/1 - 0s - loss: 0.6190 - acc: 0.0000e+00 - val_loss: 0.6995 - val_acc: 0.0000e+00
Epoch 34/50
1/1 - 0s - loss: 0.5032 - acc: 0.0000e+00 - val_loss: 0.7124 - val_acc: 0.0000e+00
Epoch 35/50
1/1 - 0s - loss: 0.5199 - acc: 0.0000e+00 - val_loss: 0.7479 - val_acc: 0.0000e+00
Epoch 36/50
1/1 - 0s - loss: 0.5283 - acc: 0.0000e+00 - val_loss: 0.7146 - val_acc: 0.0000e+00
Epoch 37/50
1/1 - 0s - loss: 0.5227 - acc: 0.0000e+00 - val_loss: 0.6946 - val_acc: 0.0000e+00
Epoch 38/50
1/1 - 0s - loss: 0.4818 - acc: 0.0000e+00 - val_loss: 0.6404 - val_acc: 0.0000e+00
Epoch 39/50
1/1 - 0s - loss: 0.4635 - acc: 0.0000e+00 - val_loss: 0.6060 - val_acc: 0.0000e+00
Epoch 40/50
1/1 - 0s - loss: 0.4405 - acc: 0.0000e+00 - val_loss: 0.6063 - val_acc: 0.0000e+00
Epoch 41/50
1/1 - 0s - loss: 0.4395 - acc: 0.0000e+00 - val_loss: 0.6093 - val_acc: 0.0000e+00
Epoch 42/50
1/1 - 0s - loss: 0.4369 - acc: 0.0000e+00 - val_loss: 0.6352 - val_acc: 0.0000e+00
Epoch 43/50
1/1 - 0s - loss: 0.4165 - acc: 0.0000e+00 - val_loss: 0.6561 - val_acc: 0.0000e+00
Epoch 44/50
1/1 - 0s - loss: 0.3748 - acc: 0.0000e+00 - val_loss: 0.6558 - val_acc: 0.0000e+00
Epoch 45/50
1/1 - 0s - loss: 0.3929 - acc: 0.0000e+00 - val_loss: 0.6668 - val_acc: 0.0000e+00
Epoch 46/50
1/1 - 0s - loss: 0.3927 - acc: 0.0000e+00 - val_loss: 0.6897 - val_acc: 0.0000e+00
Epoch 47/50
1/1 - 0s - loss: 0.3800 - acc: 0.0000e+00 - val_loss: 0.7172 - val_acc: 0.0000e+00
Epoch 48/50
1/1 - 0s - loss: 0.3637 - acc: 0.0000e+00 - val_loss: 0.7382 - val_acc: 0.0000e+00
Epoch 49/50
1/1 - 0s - loss: 0.3720 - acc: 0.0000e+00 - val_loss: 0.7558 - val_acc: 0.0000e+00
Epoch 50/50
1/1 - 0s - loss: 0.3790 - acc: 0.0000e+00 - val_loss: 0.8127 - val_acc: 0.0000e+00
1/1 [==============================] - 0s 487us/step - loss: 0.3245 - acc: 0.0000e+00
1/1 [==============================] - 0s 266us/step - loss: 0.8127 - acc: 0.0000e+00

Train Set Metrics of the trained model:
        loss: 0.3245
        acc: 0.0000

Test Set Metrics of the trained model:
        loss: 0.8127
        acc: 0.0000
```

**Comment by huonw** [comment] 2020-07-10 00:10
Thanks for filing an issue. The fact it's failing catastrophically suggests there's some serious misconfiguration, not even just random classification. I can reproduce it, and, on Google Colab, it looks like this works in 0.9.0 (when it was first added), but fails in 0.10.0 (and beyond). I'm going to try to bisect to find what the cause was.

**Comment by davidho27941** [comment] 2020-07-10 00:14
@huonw Thanks for your reply.
I was trying ver. 0.12.0 in both Colab and local workstation. all of them present the same performance.
The performance has been recorded at https://hackmd.io/@davidho9713/By7rLa4yP.
In your words, maybe I should try an earlier version for reproduction?

Best,
David

**Comment by huonw** [comment] 2020-07-10 00:17
Yeah, version 0.9 worked for me. However, I wouldn't recommend going so far back in time: there's been many usability, speed and memory use improvements between 0.9 and the latest 1.2 version. I'm working on narrowing down the problem now and will hopefully have more understanding and maybe a fix in an hour (if not, I'll let you know).

**Comment by davidho27941** [comment] 2020-07-10 00:18
@huonw 
Thank you very much!
Looking forward to your announcement!

Many thanks and best regards,
David

**Comment by huonw** [comment] 2020-07-10 01:21
It looks like this was caused by the update from TensorFlow 2.0 to 2.1: 36c2a493f457902af1373150ff8eb6564c6d8492. 

Unfortunately, current GCN link prediction demo doesn't work with TensorFlow 2.0 due to a bug in TensorFlow: the `predict` and `fit` methods don't properly support the Keras `Sequence` values used. However, the `..._generator` methods like `fit_generator` do work. That is, one **workaround** is:

- install tensorflow 2.0 (like `pip install tensorflow==2.0.2`)
- use `fit_generator`, `predict_generator`, `evaluate_generator` instead of `fit`, `predict`, `evaluate`

This is suboptimal, since there are various bugs that affect StellarGraph and are fixed in TensorFlow 2.1 and 2.2, and because those `..._generator` methods are deprecated.

I haven't narrowed down the exact cause yet, but am still looking at it.

<details><summary>Bisect info, for reference</summary>

```
$ git bisect log
# bad: [e13075bd6eccc0d01fedd489f02a895cb2acc6d6] Release 0.10.0
# good: [d1499f61a42db8bef4db6b0f0d7d74d673bc2e20] Release 0.9.0
git bisect start 'v0.10.0' 'v0.9.0'
# good: [a120fa0be92489b20bd32ef99d65110a167370e7] Speed up notebooks with Papermill to add them to CI (#820) (#860)
git bisect good a120fa0be92489b20bd32ef99d65110a167370e7
# bad: [bd55000a9ffc759aa0e20ceeb0d572fb52dd0d59] Test for warning about from_networkx 0-vector feature default (#897)
git bisect bad bd55000a9ffc759aa0e20ceeb0d572fb52dd0d59
# bad: [6688f5eb4ff80d7a2d2a27190ebe4d1d71689b06] Add Neo4j neighbourhood sampling for GraphSAGE (#799)
git bisect bad 6688f5eb4ff80d7a2d2a27190ebe4d1d71689b06
# good: [ceda25a21d8ea8a402b51d7cc6e7653cc1ef6f06] Add remaining notebooks to CI that were too slow to test (#820) (#874)
git bisect good ceda25a21d8ea8a402b51d7cc6e7653cc1ef6f06
# good: [50bb3e2b9aac5af831caa444d36f8304f4fa3be8] Install papermill as a test dependency (#878)
git bisect good 50bb3e2b9aac5af831caa444d36f8304f4fa3be8
# bad: [bbd6a924b8e3d482180ad04ef0116d0efbbcce6c] Check notebook formatting in its own step on CI (#877)
git bisect bad bbd6a924b8e3d482180ad04ef0116d0efbbcce6c
# bad: [36c2a493f457902af1373150ff8eb6564c6d8492] Remove pinning to tensorflow 2.0 to update to latest tensorflow (currently 2.1.0) (#875)
git bisect bad 36c2a493f457902af1373150ff8eb6564c6d8492
# first bad commit: [36c2a493f457902af1373150ff8eb6564c6d8492] Remove pinning to tensorflow 2.0 to update to latest tensorflow (currently 2.1.0) (#875)
```

Each step was assessed by:

- loading: https://colab.research.google.com/github/stellargraph/stellargraph/blob/$COMMIT/demos/link-prediction/gcn/cora-gcn-links-example.ipynb
- adding a first cell: `%pip install git+https://github.com/stellargraph/stellargraph.git@$COMMIT`
- running the whole notebook and observing the training metrics

</details>

**Comment by davidho27941** [comment] 2020-07-10 03:27
Sorry, I got a little bit confusing.

> install tensorflow 2.0 (like pip install tensorflow==2.0.2)

But stellargraph ver.1.2.1 is base on TF >= 2.1.0, right?
Did you mean I can run stellargraph with TF 2.0? or I should use 0.10.0 or 0.11.0 ?

**Comment by huonw** [comment] 2020-07-10 03:30
>  Did you mean I can run stellargraph with TF 2.0?

Yes, this would be overriding stellargraph's dependency specification with TF 2.0 because we "know what we are doing".

The main reason that TF >= 2.1 is specified is the problem with the non-`..._generator` methods on Keras `Model`s that I mentioned, and we can manually work around that by using `fit_generator` instead of `fit`.

**Comment by davidho27941** [comment] 2020-07-10 03:33
ok, let me have a try later.
Thanks for suggestion!

**Comment by huonw** [comment] 2020-07-10 07:26
I haven't been able to make any progress on this today, so any further debugging by me will have to wait until Monday next week (AEST).

**Comment by davidho27941** [comment] 2020-07-10 07:28
@huonw 

It's ok. Thanks for helping me so much.
BTW, I succeed to run GCN link pred. by stellargraph 1.2.1 with TF 2.0

Best,
David

**Comment by huonw** [comment] 2020-07-13 22:58
It looks like this may've been caused by the meaning of the `acc` metric changing between TF 2.0 and TF 2.1. Using `acc` as a metric name ends up having special cases (that is, it's not the same as `tf.keras.metrics.get("acc")`), where it tries to deduce whether binary, categorical or sparse categorical accuracy is the appropriate one, based on the shape of the input tensors (example of this logic, in TF 2.2: https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/engine/compile_utils.py#L423-L477 ).

The binary-or-categorical decision seems to be driven by whether the last dimension is 1 or not. For the GCN link prediction example, there's the extra batch dimension of size 1, meaning the binary prediction output is of shape `(1, 2708, 1)` (for cora with 2708 nodes), but this is flattened to `(1, 2708)` in the following line:

```python
prediction = keras.layers.Reshape((-1,))(prediction)
```

This means that Keras thinks that the output is categorical (with 2708 categories) and thus categorical accuracy is used for the `acc` metric. (Other link prediction examples do not do this flattening, e.g. GraphSAGE has predictions of shape `(batch size, 1)`, which is correct for Keras's inference.)

Thus, this can be fixed in two ways:

- replace the `acc`  metric with `binary_accuracy`, so it's`model.compile(..., metrics=["binary_accuracy"])`
- remove the `Reshape`ing, to have the prediction output have shape `(1, num nodes, 1)` instead of `(1, num nodes)`

This seems to just be a 'surface' issue with the calculation and display of the `acc` metric, but the model is still being trained correctly and performs predictions correctly.

I don't quite understand why the behaviour of `acc` seems to have changed between TF 2.0 and TF 2.1, I'll have a quick look but I'm not entirely sure it matters too much.

I'll open a PR to fix this in the demo later today, unless someone beats me to it.

(Unfortunately I'd done all investigation this yesterday, but I couldn't post the comment because GitHub was having problems. Thanks for waiting!)

**Comment by huonw** [comment] 2020-07-14 01:53
Ah, I think this is actually caused by TF 2.2, _not_ TF 2.1. The commit that had the failure (https://github.com/stellargraph/stellargraph/commit/36c2a493f457902af1373150ff8eb6564c6d8492) relaxes the requirement from `tensorflow>=2.0.0, <2.1.0` to `tensorflow>=2.0.1` , meaning that `tensorflow==2.2.0` gets installed now (so this notebook worked in StellarGraph versions 0.10 to 1.0, at the time of their release).

It looks like TF 2.2 dramatically changed how metrics work internally, including how the `acc` name is computed. In particular, it changes the `is_binary_crossentropy` vs. `is_binary` decision:

- TF 2.1: https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/engine/training_utils.py#L1094-L1133
  ```python
  is_binary_crossentropy = (
      isinstance(loss_fn, losses.BinaryCrossentropy) or
      (isinstance(loss_fn, losses.LossFunctionWrapper) and
       loss_fn.fn == losses.binary_crossentropy))
  ...
    if output_shape[-1] == 1 or is_binary_crossentropy:
  ```
- TF 2.2: https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/engine/compile_utils.py#L423-L477
  ```python
  is_binary = y_p_last_dim == 1
  ...
    if is_binary
  ```

That is, TF 2.1 introspects the loss function and notices that we're using binary cross-entropy (despite the last dimension being > 1), while TF 2.2 does not, and just looks at the last dimension. This change in behaviour actually also explicitly violates the documentation for the `metrics` to [the `Model.compile` method](https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile):

> When you pass the strings 'accuracy' or 'acc', we convert this to one of tf.keras.metrics.BinaryAccuracy, tf.keras.metrics.CategoricalAccuracy, tf.keras.metrics.SparseCategoricalAccuracy based on the loss function used and the model output shape. We do a similar conversion for the strings 'crossentropy' and 'ce' as well. 

I filed https://github.com/tensorflow/tensorflow/issues/41361 about this mismatch/regression.

**Comment by davidho27941** [comment] 2020-07-14 07:26
HI,

Thank you for digging so deep into this problem.

So the main problem is base on the library difference between TF2.0, TF2.1, and TF2.2. 
To fix this problem properly, we need to wait for the response of [tensorflow/tensorflow#41361](https://github.com/tensorflow/tensorflow/issues/41361). 

What we can do now is to:

- Use TF2.0 with stellargraph v1.2.1 and replace `fit`, `evaluate`, and `predict` by `xx_generator`.
- Replace the acc metric with binary_accuracy, so it's `model.compile(..., metrics=["binary_accuracy"])`
- Remove the `Reshapeing`, to have the prediction output have a shape `(1, num nodes, 1)` instead of `(1, num nodes)`.

Please feel free to point me out if I have any misconceptions.

Many thanks and best regards,
David

**Comment by huonw** [comment] 2020-07-14 23:08
You're pretty much correct, yeah.

I'll rephrase the options, starting from the best/easiest:

1. replace `acc` with `binary_accuracy`: `model.compile(..., metrics=["binary_accuracy"])` (which is what #1770 does in the demo in the repo)
2. remove the `Reshape`ing
3. use TF 2.1 with stellargraph 1.2.1 (that is, version 2.1 seems to work for me, not just 2.0), where `fit`, `evaluate` and `predict` should work too (no need to use `..._generator`)

The last is much better than using TF 2.0, and I only noticed in my previous comment when working out the true underlying problem.

**Closed as completed** 2020-07-15 00:23 UTC
Labels: bug, sg-library, doc
