### ISSUE TITLE
Edge Splitter for directed graphs

### ISSUE THREAD

**Issue by rmant** [stellargraph/stellargraph#1861] opened 2021-02-03 15:45 UTC
### Description

I'm training a link classification algorithm for a directed graph. However, when I try to use the stellargraph.data.EdgeSplitter.train_test_split module, I'm getting an error:
`NetworkXNotImplemented: not implemented for directed type`

This shouldn't be something too hard to solve since an edge splitter shouldn't be very different for a directed or an undirected graph.

### User Story

**As** an ML engineer

**I want to** be able to use an edge splitter with an undirected graph

**So that** I can train link classification algorithms for undirected graphs.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment] 2021-02-07 22:24
Thanks for filing an issue @rmant. This is a duplicate of https://github.com/stellargraph/stellargraph/issues/945 and so I'm going to close it in favour of that. That issue was filed as a result of experiments with directed edge-splitting in https://github.com/stellargraph/stellargraph/pull/879, which were removed as it wasn't clear how well they were working at all (https://github.com/stellargraph/stellargraph/pull/879#issuecomment-590155731).  The changes made in that PR were fully reverted in https://github.com/stellargraph/stellargraph/pull/879/commits/1a3af2bc3f93ae38487498603bff688c1fd76c77 , but could be revived and tested explicitly.

**Closed as completed** 2021-02-07 22:25 UTC
Labels: enhancement, sg-library
