### ISSUE TITLE
import stellargraph as sg failed

### ISSUE THREAD

**Issue by wmymartin** [stellargraph/stellargraph#647] opened 2020-01-09 06:47 UTC
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-85332ee1c664> in <module>
      5 import random
      6 
----> 7 import stellargraph as sg
      8 from stellargraph.data import EdgeSplitter
      9 from stellargraph.mapper import GraphSAGELinkGenerator

~/tensorflow/venv/lib/python3.7/site-packages/stellargraph/__init__.py in <module>
     18 
     19 # Import modules
---> 20 from stellargraph import mapper, layer, utils
     21 
     22 # Top-level imports

~/tensorflow/venv/lib/python3.7/site-packages/stellargraph/mapper/__init__.py in <module>
     24 
     25 # Expose the mappers
---> 26 from .node_mappers import *
     27 from .link_mappers import *

~/tensorflow/venv/lib/python3.7/site-packages/stellargraph/mapper/node_mappers.py in <module>
     39 from tensorflow.keras import backend as K
     40 from functools import reduce
---> 41 from tensorflow.keras.utils import Sequence
     42 
     43 from ..data.explorer import (

ModuleNotFoundError: No module named 'tensorflow.keras.utils'

**Comment by huonw** [comment] 2020-01-09 22:47
Hi, thanks for the issue @wmymartin!

My suspicion here is that `tensorflow` isn't the right version for `stellargraph`. Could you give some more details about how you installed `stellargraph`? If you install things via pip, could you paste the output of `pip freeze` here?

**Comment by wmymartin** [comment] 2020-01-12 13:26
@huonw i installed via pip using virtualenv, and 'pip freeze' result is 
absl-py==0.8.1
alabaster==0.7.12
appnope==0.1.0
astor==0.8.0
Babel==2.7.0
backcall==0.1.0
bleach==3.0.2
boto==2.49.0
boto3==1.10.49
botocore==1.13.49
certifi==2019.9.11
chardet==3.0.4
colorama==0.4.1
commonmark==0.9.1
contextlib2==0.5.5
coverage==4.5.4
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
docopt==0.6.2
docutils==0.15.2
entrypoints==0.2.3
future==0.18.2
gast==0.2.2
gensim==3.8.1
google-pasta==0.1.7
graphframes==0.6
grpcio==1.24.1
guzzle-sphinx-theme==0.7.11
h5py==2.10.0
hdfs==2.5.8
hyperopt==0.1.2
idna==2.8
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.2
Jinja2==2.10
jmespath==0.9.4
joblib==0.13.2
json-tricks==3.13.4
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.0
matplotlib==3.1.1
mistune==0.8.4
mock==3.0.5
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.3
nni==1.1
nose==1.3.7
notebook==5.7.4
numpy==1.17.0
opt-einsum==3.1.0
packaging==19.2
pandas==0.25.0
pandocfilters==1.4.2
parso==0.3.1
patsy==0.5.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==6.2.1
progressbar==2.5
prometheus-client==0.5.0
prompt-toolkit==2.0.7
protobuf==3.10.0
psutil==5.6.5
ptyprocess==0.6.0
py4j==0.10.8.1
pydotplus==2.0.2
Pygments==2.3.1
pymongo==3.9.0
pyparsing==2.4.2
pyspark==2.4.0
pyspark-stubs==2.4.0.post6
python-dateutil==2.7.5
PythonWebHDFS==0.2.3
pytz==2019.2
PyYAML==5.3
pyzmq==17.1.2
qtconsole==4.4.3
recommonmark==0.6.0
requests==2.22.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
s3transfer==0.2.1
schema==0.7.1
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
sh==1.12.14
simplejson==3.16.0
six==1.12.0
sklearn==0.0
sklearn-pandas==1.8.0
sklearn2pmml==0.49.1
skope-rules==1.0.0
smart-open==1.9.0
snowballstemmer==2.0.0
Sphinx==2.2.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
statsmodels==0.10.1
stellargraph==0.8.3
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
torch==1.3.1
torchvision==0.4.2
tornado==5.1.1
tqdm==4.38.0
traitlets==4.3.2
urllib3==1.25.6
virtualenv==16.7.5
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.4.2
wrapt==1.11.2

**Comment by huonw** [comment] 2020-01-12 22:52
Thanks for the info. Unfortunately, I cannot reproduce the problem. I created by own fresh virtualenv and installed all those packages:

```shell
# create a requirements file
pbpaste > requirements.txt # (on macOS, after copying the above text)

# create a fresh virtualenv
pyenv virtualenv 3.6.9 issue-647 # (using pyenv, but can be anything that makes a new virtualenv)
pyenv activate issue-647

# install packages
pip install numpy==1.17.0 scipy==1.3.1 # need to be already installed to install slope-rules
pip install -r requirements.txt

# confirm that the packages are exactly the same 
diff <(pip freeze) requirements.txt # no output
```

Given that setup, `import stellargraph` (with or without the renaming `as sg`) works fine for me:

```python
# test.py
import stellargraph as sg
print("Version:", g.version.__version__)
```
```
$ python test.py
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/wil9dw/.pyenv/versions/issue-647/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Version: 0.8.3
```

I tested the above on:

- macOS (10.14.5) with Python 3.6.9
- in the `python:3.6` docker image (using docker-for-mac): `docker run --rm -it -v $PWD:/app python:3.6 bash` and then running the installation commands onwards (no need to create a virtualenv because it starts clean)

Could you give us more information about the system you are using?

- Operating system (and version)
- Python version (`python --version`)

**Comment by wmymartin** [comment] 2020-01-13 03:30
@huonw 
Operating system: mac catalina 10.15.2
Python version 3.7.2

i have installed tensorflow (version 2.0) before installing stellargraph , i do not know Whether it has an impact
the pip log is 
"
Installing collected packages: tensorflow-estimator, tensorboard, tensorflow, boto, jmespath, botocore, s3transfer, boto3, smart-open, gensim, networkx, stellargraph
  Found existing installation: tensorflow-estimator 2.0.0
    Uninstalling tensorflow-estimator-2.0.0:
      Successfully uninstalled tensorflow-estimator-2.0.0
  Found existing installation: tensorboard 2.0.0
    Uninstalling tensorboard-2.0.0:
      Successfully uninstalled tensorboard-2.0.0
  Found existing installation: tensorflow 2.0.0
    Uninstalling tensorflow-2.0.0:
      Successfully uninstalled tensorflow-2.0.0
  Found existing installation: networkx 2.4
    Not uninstalling networkx at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages, outside environment /Users/martin/tensorflow/venv/bin/..

"

**Comment by huonw** [comment] 2020-01-13 04:59
Thanks! I tried again using the `python:3.7.2` docker image and a 3.7.2 installation locally, and both of them worked, the same as my comment above.


> i have installed tensorflow (version 2.0) before installing stellargraph , i do not know Whether it has an impact

A different version of tensorflow might be the cause, but that log there is saying that it is removing those old versions, and the `pip freeze` output says `tensorflow==1.14.0`, meaning the virtual environment has the correct version (as required by stellargraph 0.8.3):

https://github.com/stellargraph/stellargraph/blob/12f85e00c0d0c584719be39d33d10d080ae18b95/setup.py#L24

---

Could you try creating a new virtual environment and installing the requirements like I did above, on your machine?

**Comment by wmymartin** [comment] 2020-01-13 05:58
ok，i will have a try , thanks a lot @huonw

**Comment by huonw** [comment] 2020-01-20 23:45
Hi @wmymartin, did you get it to work? Is there anything more I can help with?

**Comment by huonw** [comment] 2020-03-06 04:00
Hello again @wmymartin, just double checking if there's any more help you need? If not, I'll close this issue.

**Closed** 2020-03-09 01:24 UTC
Labels: bug, external, sg-library
